### ISSUE TITLE
Skip repo if error is risen

### ISSUE THREAD

**Issue by yaniksoeltzer** [yaniksoeltzer/git_inspector#25]
Even though I have multiple repositories in the directory, only the first one is reported, than an error is risen.
Additionaly look into the error.

```
1 git repositories found. Everything looks fine :D
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/USER/.local/lib/python3.9/site-packages/git_inspector/__main__.py", line 8, in <module>
    exit_code = generate_reports(absolute_paths, reporter)
  File "/home/USER/.local/lib/python3.9/site-packages/git_inspector/generate_reports.py", line 18, in generate_reports
    for report in reports:
  File "/home/USER/.local/lib/python3.9/site-packages/git_inspector/reports/__init__.py", line 19, in get_reports
    report = get_report(repo)
  File "/home/USER/.local/lib/python3.9/site-packages/git_inspector/reports/unpushed.py", line 13, in get_unpushed_report
    unpushed_branches = get_unpushed_branches(repo)
  File "/home/USER/.local/lib/python3.9/site-packages/git_inspector/reports/unpushed.py", line 31, in get_unpushed_branches
    if is_ancestors_of(ancestor=remote_commit, commit=local_commit):
  File "/home/USER/.local/lib/python3.9/site-packages/git_inspector/common.py", line 35, in is_ancestors_of
    return depth_search_commit([commit], [], ancestor) is not None
  File "/home/USER/.local/lib/python3.9/site-packages/git_inspector/common.py", line 52, in depth_search_commit
    dept = depth_search_commit(new_fringe, visited, goal_node, cur_dept+1)
  File "/home/USER/.local/lib/python3.9/site-packages/git_inspector/common.py", line 48, in depth_search_commit
    f_parents = fring.parents
  File "/home/USER/.local/lib/python3.9/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/home/USER/.local/lib/python3.9/site-packages/git/objects/commit.py", line 183, in _set_cache_
    _binsha, _typename, self.size, stream = self.repo.odb.stream(self.binsha)
  File "/home/USER/.local/lib/python3.9/site-packages/git/db.py", line 48, in stream
    hexsha, typename, size, stream = self._git.stream_object_data(bin_to_hex(binsha))
  File "/home/USER/.local/lib/python3.9/site-packages/git/cmd.py", line 1206, in stream_object_data
    hexsha, typename, size = self.__get_object_header(cmd, ref)
  File "/home/USER/.local/lib/python3.9/site-packages/git/cmd.py", line 1178, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/home/USER/.local/lib/python3.9/site-packages/git/cmd.py", line 1140, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'7692881d2a61a4ba47eeef5d7827c0d2cb896def' could not be resolved, git returned: b'7692881d2a61a4ba47eeef5d7827c0d2cb896def missing
```

**Comment by yaniksoeltzer** [comment]
The error is thrown by the `unpushed branch` reporter if the remote branch is gone.
In this case, the remote repo was a file.
```
## master...origin/master [gone]
```
